# Generated by Django 6.0.3 on 2026-06-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reveiw_text',
            new_name='review_text',
        ),
    ]
